Translate several pinia interfaces
vuejs-ua/pinia pull request #52
Opened 2023-10-05 13:20 UTC by OlesyaKlochko

There are several translated API interfaces:
- MapStoresCustomization
- Pinia
- PiniaCustomProperties
- PiniaCustomStateProperties
- PiniaPlugin

2023-10-05 13:21 UTC, OlesyaKlochko commented on packages/docs/api/interfaces/pinia.Pinia.md
> +## Ієрархія
```suggestion

## Ієрархія
```

2023-10-05 13:33 UTC, nazar1ua requested changes

2023-10-05 13:33 UTC, nazar1ua commented on packages/docs/api/interfaces/pinia.MapStoresCustomization.md
> +Інтерфейс, що дозволяє налаштовувати мапу допоміжних функцій. Розширте
Мені здається, що тут `map helpers` — це не `мапа допоміжних функцій`. Це типу допоміжні функції для `map`

2023-10-05 13:33 UTC, nazar1ua commented on packages/docs/api/interfaces/pinia.Pinia.md
> +#### Типи оголошення
```suggestion
#### Оголошення типів
```

2023-10-05 13:33 UTC, nazar1ua commented on packages/docs/api/interfaces/pinia.PiniaPlugin.md
> +або нічого не повертає.
```suggestion
або не повертає нічого.
```

2023-10-05 17:14 UTC, matrunchyk commented on packages/docs/api/interfaces/pinia.MapStoresCustomization.md
> +Інтерфейс, що дозволяє налаштовувати мапу допоміжних функцій. Розширте
Погоджуюсь з Назаром — тут радше йдеться про функції, а не про мапу

2023-10-06 14:13 UTC, OlesyaKlochko commented on packages/docs/api/interfaces/pinia.MapStoresCustomization.md
> +Інтерфейс, що дозволяє налаштовувати мапу допоміжних функцій. Розширте
```suggestion
Інтерфейс, що дозволяє налаштовувати допоміжні функції для `map`. Розширте 
```

2023-10-06 14:13 UTC, OlesyaKlochko commented on packages/docs/api/interfaces/pinia.MapStoresCustomization.md
> +Інтерфейс, що дозволяє налаштовувати мапу допоміжних функцій. Розширте
Погоджуюсь з вами. A 'map' ми перекладаємо чи лишаємо?

2023-10-06 14:16 UTC, OlesyaKohivchak commented on packages/docs/api/interfaces/pinia.PiniaPlugin.md
> +або нічого не повертає.
Маю сумніви на рахунок цієї пропозиції, мені мій варіант якось краще звучить наче, але вже стільки разів прочитала, що не відчуваю. Давай ще запитаємо @matrunchyk 🙂

2023-10-06 15:30 UTC, matrunchyk commented on packages/docs/api/interfaces/pinia.MapStoresCustomization.md
> +Інтерфейс, що дозволяє налаштовувати мапу допоміжних функцій. Розширте
я б певно лишив, щоб перегукувалось з назвою інтерфейсу.

2023-10-06 15:31 UTC, matrunchyk commented on packages/docs/api/interfaces/pinia.PiniaPlugin.md
> +або нічого не повертає.
мені і так, і так ок насправді)))

2023-10-06 15:31 UTC, matrunchyk approved these changes

2023-10-06 15:31 UTC, merged